port: 8888
# strategy: "round-robin"
# strategy: "least-conn"
strategy: "weighted-round-robin"
servers:
  - address: "http://localhost:8080"
    weight: 5
    heart-beat:
      interval: 1000
      endpoint: "/health"
  - address: "http://localhost:8081"
    weight: 2
    heart-beat:
      interval: 1000
      endpoint: "/health"
  - address: "http://localhost:8082"
    weight: 1
    heart-beat:
      interval: 1000
      endpoint: "/health"
  - address: "http://localhost:8083"
    weight: 1
    heart-beat:
      interval: 1000
      endpoint: "/health"
